# Package Imports
from gmdkit.serialization.type_cast import to_string, zip_string
from gmdkit.models.prop.list import IntList
from gmdkit.models.prop.gzip import ObjectString, ReplayString


LEVEL_DECODERS = {
    'k4': ObjectString,
    'k34': ReplayString,
    'k88': IntList.from_string,
    'k91': IntList.from_string,
    'k104': IntList.from_string,
    'k105': IntList.from_string,
    'k109': IntList.from_string,
    'k110': IntList.from_string,
}


LEVEL_ENCODERS = {
    'k4': zip_string,
    'k34': zip_string,
    'k88': to_string,
    'k91': to_string,
    'k104': to_string,
    'k105': to_string,
    'k109': to_string,
    'k110': to_string,
}


LEVEL_TYPES = {
    'k1': int,
    'k2': str,
    'k3': str,
    'k4': ObjectString,
    'k5': str,
    'k6': int,
    'k7': int,
    'k8': int,
    'k9': int,
    'k10': int,
    'k11': int,
    'k12': int,
    'k16': int,
    'k17': int,
    'k18': int,
    'k19': int,
    'k20': int,
    'k21': int,
    'k22': int,
    'k23': int,
    'k24': int,
    'k26': int,
    'k27': int,
    'k34': ReplayString,
    'k36': int,
    'k37': int,
    'k39': int,
    'k40': int,
    'k41': int,
    'k42': int,
    'k45': int,
    'k46': int,
    'k48': int,
    'k50': int,
    'k51': int,
    'k52': int,
    'k53': int,
    'k54': int,
    'k60': int,
    'k64': int,
    'k66': int,
    'k67': str,
    'k71': int,
    'k74': int,
    'k75': int,
    'k76': int,
    'k80': int,
    'k81': int,
    'k83': int,
    'k84': int,
    'k85': int,
    'k86': int,
    'k87': int,
    'k88': IntList,
    'k90': int,
    'k91': IntList,
    'k95': int,
    'k101': str,
    'k102': int,
    'k103': int,
    'k104': IntList,
    'k105': IntList,
    'k106': int,
    'k107': int,
    'k108': int,
    'k109': IntList,
    'k110': IntList,
    'k111': int,
    'kI1': float,
    'kI2': float,
    'kI3': float,
    'kI4': int,
    'kI5': int,
    'kI7': float,
    'kCEK': int,
}