# Package Imports
from gmdkit.utils import enums
from gmdkit.serialization.type_cast import decode_text, encode_text, get_string
from gmdkit.models.prop.list import IntList
from gmdkit.models.prop.pos_list import PositionList
from gmdkit.models.prop.gzip import ObjectString, ReplayString


LEVEL_DECODERS = {
    'k3': decode_text,
    'k4': ObjectString,
    'k7': enums.LevelDifficulty,
    'k8': enums.OfficialSongs,
    'k10': enums.LevelRating,
    'k21': enums.LevelType,
    'k34': ReplayString,
    'k75': enums.EpicRating,
    'k76': enums.DemonRating,
    'k88': IntList.from_string,
    'k91': IntList.from_string,
    'k101': PositionList.from_string,
    'k104': IntList.from_string,
    'k105': IntList.from_string,
    'k109': IntList.from_string,
    'k110': IntList.from_string,
    'k119': ReplayString,
    'k120': ReplayString,
    'k125': enums.ToggleCBS,
}


LEVEL_ENCODERS = {
    'k3': encode_text,
    'k4': get_string,
    'k34': get_string,
    'k88': IntList.to_string,
    'k91': IntList.to_string,
    'k101': PositionList.to_string,
    'k104': IntList.to_string,
    'k105': IntList.to_string,
    'k109': IntList.to_string,
    'k110': IntList.to_string,
    'k119': get_string,
    'k120': get_string,
}


LEVEL_TYPES = {
    'k1': int,
    'k2': str,
    'k3': str,
    'k4': ObjectString,
    'k5': str,
    'k6': int,
    'k7': enums.LevelDifficulty,
    'k8': enums.OfficialSongs,
    'k9': int,
    'k10': enums.LevelRating,
    'k11': int,
    'k16': int,
    'k17': int,
    'k18': int,
    'k19': int,
    'k20': int,
    'k21': enums.LevelType,
    'k22': int,
    'k23': int,
    'k24': int,
    'k26': int,
    'k27': int,
    'k34': ReplayString,
    'k36': int,
    'k37': int,
    'k41': int,
    'k42': int,
    'k45': int,
    'k46': int,
    'k48': int,
    'k50': int,
    'k60': int,
    'k64': int,
    'k66': int,
    'k67': str,
    'k71': int,
    'k74': int,
    'k75': enums.EpicRating,
    'k76': enums.DemonRating,
    'k80': int,
    'k81': int,
    'k83': int,
    'k84': int,
    'k85': int,
    'k86': int,
    'k87': int,
    'k88': IntList,
    'k90': int,
    'k91': IntList,
    'k95': int,
    'k101': PositionList,
    'k102': int,
    'k103': int,
    'k104': IntList,
    'k105': IntList,
    'k106': int,
    'k107': int,
    'k108': int,
    'k109': IntList,
    'k110': IntList,
    'k111': int,
    'k115': int,
    'k116': int,
    'k117': int,
    'k118': int,
    'k119': ReplayString,
    'k120': ReplayString,
    'k121': int,
    'k122': int,
    'k125': enums.ToggleCBS,
    'kI1': float,
    'kI2': float,
    'kI3': float,
    'kI4': int,
    'kI5': int,
    'kI7': float,
}