# Package Imports
from gmdkit.serialization.type_cast import to_string, zip_string
from gmdkit.models.prop.list import IntList
from gmdkit.models.prop.gzip import ObjectString, ReplayString


LIST_DECODERS = {
    'k1': nan,
    'k100': nan,
    'k11': nan,
    'k113': nan,
    'k114': nan,
    'k15': bool,
    'k16': nan,
    'k2': nan,
    'k21': nan,
    'k22': nan,
    'k27': nan,
    'k3': nan,
    'k42': nan,
    'k46': nan,
    'k47': nan,
    'k5': nan,
    'k60': nan,
    'k7': nan,
    'k79': nan,
    'k82': nan,
    'k83': nan,
    'k84': nan,
    'k94': nan,
    'k96': IntList.from_string,
    'k97': nan,
    'k98': nan,
    'k99': nan,
    'kCEK': nan,
}


LIST_ENCODERS = {
    'k1': nan,
    'k100': nan,
    'k11': nan,
    'k113': nan,
    'k114': nan,
    'k15': int,
    'k16': nan,
    'k2': nan,
    'k21': nan,
    'k22': nan,
    'k27': nan,
    'k3': nan,
    'k42': nan,
    'k46': nan,
    'k47': nan,
    'k5': nan,
    'k60': nan,
    'k7': nan,
    'k79': nan,
    'k82': nan,
    'k83': nan,
    'k84': nan,
    'k94': nan,
    'k96': to_string,
    'k97': nan,
    'k98': nan,
    'k99': nan,
    'kCEK': nan,
}


LIST_TYPES = {
    'k1': int,
    'k100': nan,
    'k11': int,
    'k113': int,
    'k114': int,
    'k15': bool,
    'k16': int,
    'k2': str,
    'k21': int,
    'k22': int,
    'k27': nan,
    'k3': str,
    'k42': int,
    'k46': int,
    'k47': nan,
    'k5': str,
    'k60': int,
    'k7': int,
    'k79': nan,
    'k82': nan,
    'k83': int,
    'k84': int,
    'k94': nan,
    'k96': IntList,
    'k97': nan,
    'k98': int,
    'k99': int,
    'kCEK': int,
}