# Package Imports
from gmdkit.utils import enums
from gmdkit.serialization.type_cast import (
    to_bool, from_bool, 
    from_float,
    decode_text, encode_text,
    to_numkey
    )
from gmdkit.serialization.classes import DictField, FieldMetaclass
from gmdkit.serialization.mixins import DictDecoderMixin
from gmdkit.models.prop.groups import IDList
from gmdkit.models.prop.events import EventList
from gmdkit.models.prop.sequence import SequenceList
from gmdkit.models.prop.random import RandomWeightsList
from gmdkit.models.prop.remaps import RemapList
from gmdkit.models.prop.guideline import GuidelineList
from gmdkit.models.prop.hsv import HSV
from gmdkit.models.prop.particle import Particle
from gmdkit.models.prop.color import Color, ColorList

class FieldLoaderMixin(DictDecoderMixin, metaclass=FieldMetaclass):
    KEY_DECODER = to_numkey
    KEY_ENCODER = str

    object_id: int = DictField(key=1, decoder=int)

FieldLoaderMixin.add_field(key=2, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=3, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=4, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=5, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=6, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=7, decoder=int)
FieldLoaderMixin.add_field(key=8, decoder=int)
FieldLoaderMixin.add_field(key=9, decoder=int)
FieldLoaderMixin.add_field(key=10, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=11, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=12, decoder=int)
FieldLoaderMixin.add_field(key=13, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=14, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=15, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=16, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=17, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=19, decoder=enums.OldColor)
FieldLoaderMixin.add_field(key=20, decoder=int)
FieldLoaderMixin.add_field(key=21, decoder=int)
FieldLoaderMixin.add_field(key=22, decoder=int)
FieldLoaderMixin.add_field(key=23, decoder=int)
FieldLoaderMixin.add_field(key=24, decoder=int)
FieldLoaderMixin.add_field(key=25, decoder=int)
FieldLoaderMixin.add_field(key=28, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=29, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=30, decoder=enums.Easing)
FieldLoaderMixin.add_field(key=31, decoder=decode_text, encoder=encode_text)
FieldLoaderMixin.add_field(key=32, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=34, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=35, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=36, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=41, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=42, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=43, decoder=HSV.from_string, encoder=HSV.to_string)
FieldLoaderMixin.add_field(key=44, decoder=HSV.from_string, encoder=HSV.to_string)
FieldLoaderMixin.add_field(key=45, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=46, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=47, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=48, decoder=enums.PulseColorType)
FieldLoaderMixin.add_field(key=49, decoder=HSV.from_string, encoder=HSV.to_string)
FieldLoaderMixin.add_field(key=50, decoder=int)
FieldLoaderMixin.add_field(key=51, decoder=int)
FieldLoaderMixin.add_field(key=52, decoder=enums.PulseTarget)
FieldLoaderMixin.add_field(key=54, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=55, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=56, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=57, decoder=IDList.from_string, encoder=IDList.to_string)
FieldLoaderMixin.add_field(key=58, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=59, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=60, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=61, decoder=int)
FieldLoaderMixin.add_field(key=62, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=63, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=64, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=65, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=66, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=67, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=68, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=69, decoder=int)
FieldLoaderMixin.add_field(key=70, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=71, decoder=int)
FieldLoaderMixin.add_field(key=72, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=73, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=75, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=76, decoder=int)
FieldLoaderMixin.add_field(key=77, decoder=int)
FieldLoaderMixin.add_field(key=78, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=80, decoder=int)
FieldLoaderMixin.add_field(key=81, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=82, decoder=enums.TouchMode)
FieldLoaderMixin.add_field(key=84, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=85, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=86, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=87, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=88, decoder=enums.InstantCountMode)
FieldLoaderMixin.add_field(key=89, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=90, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=91, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=92, decoder=int)
FieldLoaderMixin.add_field(key=93, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=94, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=95, decoder=int)
FieldLoaderMixin.add_field(key=96, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=97, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=98, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=99, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=100, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=101, decoder=enums.TargetAxis)
FieldLoaderMixin.add_field(key=102, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=103, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=104, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=105, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=106, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=107, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=108, decoder=int)
FieldLoaderMixin.add_field(key=110, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=111, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=112, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=113, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=114, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=115, decoder=int)
FieldLoaderMixin.add_field(key=116, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=117, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=118, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=120, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=121, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=122, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=123, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=126, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=127, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=128, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=129, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=131, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=132, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=133, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=134, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=135, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=136, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=137, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=138, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=139, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=141, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=142, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=143, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=144, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=145, decoder=Particle.from_string, encoder=Particle.to_string)
FieldLoaderMixin.add_field(key=146, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=147, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=148, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=149, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=150, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=151, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=152, decoder=RandomWeightsList.from_string, encoder=RandomWeightsList.to_string)
FieldLoaderMixin.add_field(key=153, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=154, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=155, decoder=int)
FieldLoaderMixin.add_field(key=156, decoder=int)
FieldLoaderMixin.add_field(key=157, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=159, decoder=enums.Option)
FieldLoaderMixin.add_field(key=160, decoder=enums.Option)
FieldLoaderMixin.add_field(key=161, decoder=enums.Option)
FieldLoaderMixin.add_field(key=162, decoder=enums.Option)
FieldLoaderMixin.add_field(key=163, decoder=enums.Option)
FieldLoaderMixin.add_field(key=164, decoder=enums.CameraEdge)
FieldLoaderMixin.add_field(key=165, decoder=enums.Option)
FieldLoaderMixin.add_field(key=166, decoder=enums.ArrowDir)
FieldLoaderMixin.add_field(key=167, decoder=enums.ArrowDir)
FieldLoaderMixin.add_field(key=169, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=170, decoder=int)
FieldLoaderMixin.add_field(key=171, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=172, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=173, decoder=int)
FieldLoaderMixin.add_field(key=174, decoder=enums.GradientBlending)
FieldLoaderMixin.add_field(key=175, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=176, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=177, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=179, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=180, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=181, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=182, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=183, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=184, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=185, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=186, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=187, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=188, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=189, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=190, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=191, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=192, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=193, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=194, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=195, decoder=enums.Option)
FieldLoaderMixin.add_field(key=196, decoder=enums.GradientLayer)
FieldLoaderMixin.add_field(key=197, decoder=enums.GradientLayer)
FieldLoaderMixin.add_field(key=198, decoder=enums.TargetPlayer)
FieldLoaderMixin.add_field(key=199, decoder=enums.Option)
FieldLoaderMixin.add_field(key=200, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=201, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=202, decoder=enums.GradientLayer)
FieldLoaderMixin.add_field(key=203, decoder=int)
FieldLoaderMixin.add_field(key=204, decoder=int)
FieldLoaderMixin.add_field(key=205, decoder=int)
FieldLoaderMixin.add_field(key=206, decoder=int)
FieldLoaderMixin.add_field(key=207, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=208, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=209, decoder=int)
FieldLoaderMixin.add_field(key=210, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=211, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=212, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=213, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=214, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=217, decoder=enums.EnterMode)
FieldLoaderMixin.add_field(key=218, decoder=int)
FieldLoaderMixin.add_field(key=219, decoder=int)
FieldLoaderMixin.add_field(key=220, decoder=int)
FieldLoaderMixin.add_field(key=221, decoder=int)
FieldLoaderMixin.add_field(key=222, decoder=int)
FieldLoaderMixin.add_field(key=223, decoder=int)
FieldLoaderMixin.add_field(key=224, decoder=int)
FieldLoaderMixin.add_field(key=225, decoder=int)
FieldLoaderMixin.add_field(key=231, decoder=int)
FieldLoaderMixin.add_field(key=232, decoder=int)
FieldLoaderMixin.add_field(key=233, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=234, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=235, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=236, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=237, decoder=int)
FieldLoaderMixin.add_field(key=238, decoder=int)
FieldLoaderMixin.add_field(key=239, decoder=int)
FieldLoaderMixin.add_field(key=240, decoder=int)
FieldLoaderMixin.add_field(key=241, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=242, decoder=enums.Easing)
FieldLoaderMixin.add_field(key=243, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=248, decoder=enums.Easing)
FieldLoaderMixin.add_field(key=249, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=252, decoder=int)
FieldLoaderMixin.add_field(key=253, decoder=int)
FieldLoaderMixin.add_field(key=260, decoder=int)
FieldLoaderMixin.add_field(key=261, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=262, decoder=int)
FieldLoaderMixin.add_field(key=263, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=264, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=265, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=270, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=271, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=274, decoder=IDList.from_string, encoder=IDList.to_string)
FieldLoaderMixin.add_field(key=275, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=276, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=278, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=279, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=280, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=281, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=282, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=283, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=284, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=285, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=286, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=287, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=288, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=289, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=290, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=291, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=292, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=293, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=298, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=299, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=300, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=301, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=305, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=306, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=307, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=308, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=309, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=310, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=311, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=312, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=313, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=314, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=315, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=316, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=317, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=318, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=319, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=320, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=321, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=322, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=323, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=324, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=325, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=326, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=327, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=328, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=329, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=330, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=331, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=332, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=333, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=334, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=335, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=336, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=337, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=338, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=339, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=340, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=341, decoder=int)
FieldLoaderMixin.add_field(key=343, decoder=int)
FieldLoaderMixin.add_field(key=344, decoder=int)
FieldLoaderMixin.add_field(key=345, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=346, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=347, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=348, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=349, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=350, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=351, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=352, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=353, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=354, decoder=enums.GravityMode)
FieldLoaderMixin.add_field(key=355, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=356, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=357, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=358, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=359, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=360, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=361, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=362, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=363, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=364, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=365, decoder=int)
FieldLoaderMixin.add_field(key=366, decoder=int)
FieldLoaderMixin.add_field(key=367, decoder=enums.AdvFollowMode)
FieldLoaderMixin.add_field(key=368, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=369, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=370, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=371, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=372, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=373, decoder=int)
FieldLoaderMixin.add_field(key=374, decoder=int)
FieldLoaderMixin.add_field(key=375, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=376, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=377, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=378, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=379, decoder=enums.KeyframeRefMode)
FieldLoaderMixin.add_field(key=380, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=381, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=382, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=383, decoder=int)
FieldLoaderMixin.add_field(key=385, decoder=enums.UIRef)
FieldLoaderMixin.add_field(key=386, decoder=enums.UIRef)
FieldLoaderMixin.add_field(key=387, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=388, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=389, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=390, decoder=enums.ItemLabelSpecialID)
FieldLoaderMixin.add_field(key=391, decoder=enums.ItemLabelAlignment)
FieldLoaderMixin.add_field(key=392, decoder=int)
FieldLoaderMixin.add_field(key=393, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=394, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=395, decoder=int)
FieldLoaderMixin.add_field(key=396, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=397, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=399, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=400, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=401, decoder=int)
FieldLoaderMixin.add_field(key=402, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=403, decoder=int)
FieldLoaderMixin.add_field(key=404, decoder=int)
FieldLoaderMixin.add_field(key=405, decoder=int)
FieldLoaderMixin.add_field(key=406, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=407, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=408, decoder=int)
FieldLoaderMixin.add_field(key=409, decoder=int)
FieldLoaderMixin.add_field(key=410, decoder=int)
FieldLoaderMixin.add_field(key=411, decoder=int)
FieldLoaderMixin.add_field(key=412, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=413, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=414, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=415, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=416, decoder=int)
FieldLoaderMixin.add_field(key=417, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=418, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=419, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=420, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=421, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=422, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=423, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=424, decoder=int)
FieldLoaderMixin.add_field(key=425, decoder=int)
FieldLoaderMixin.add_field(key=426, decoder=int)
FieldLoaderMixin.add_field(key=428, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=430, decoder=EventList.from_string, encoder=EventList.to_string)
FieldLoaderMixin.add_field(key=431, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=432, decoder=int)
FieldLoaderMixin.add_field(key=433, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=434, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=435, decoder=SequenceList.from_string, encoder=SequenceList.to_string)
FieldLoaderMixin.add_field(key=436, decoder=enums.SequenceMode)
FieldLoaderMixin.add_field(key=437, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=438, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=439, decoder=enums.SequenceResetType)
FieldLoaderMixin.add_field(key=440, decoder=int)
FieldLoaderMixin.add_field(key=441, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=442, decoder=RemapList.from_string, encoder=RemapList.to_string)
FieldLoaderMixin.add_field(key=443, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=444, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=445, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=446, decoder=int)
FieldLoaderMixin.add_field(key=447, decoder=int)
FieldLoaderMixin.add_field(key=448, decoder=int)
FieldLoaderMixin.add_field(key=449, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=452, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=453, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=454, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=455, decoder=int)
FieldLoaderMixin.add_field(key=456, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=457, decoder=int)
FieldLoaderMixin.add_field(key=458, decoder=enums.VolumeDirection)
FieldLoaderMixin.add_field(key=459, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=460, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=461, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=462, decoder=int)
FieldLoaderMixin.add_field(key=463, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=464, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=465, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=466, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=467, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=468, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=469, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=470, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=471, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=472, decoder=enums.TimeControlType)
FieldLoaderMixin.add_field(key=473, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=474, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=475, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=476, decoder=enums.ItemType)
FieldLoaderMixin.add_field(key=477, decoder=enums.ItemType)
FieldLoaderMixin.add_field(key=478, decoder=enums.ItemType)
FieldLoaderMixin.add_field(key=479, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=480, decoder=enums.ItemOperation)
FieldLoaderMixin.add_field(key=481, decoder=enums.ItemOperation)
FieldLoaderMixin.add_field(key=482, decoder=enums.ItemOperation)
FieldLoaderMixin.add_field(key=483, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=484, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=485, decoder=enums.ItemRoundOp)
FieldLoaderMixin.add_field(key=486, decoder=enums.ItemRoundOp)
FieldLoaderMixin.add_field(key=487, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=488, decoder=int)
FieldLoaderMixin.add_field(key=489, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=490, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=491, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=492, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=493, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=494, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=495, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=496, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=497, decoder=enums.SingleColorMode)
FieldLoaderMixin.add_field(key=498, decoder=int)
FieldLoaderMixin.add_field(key=499, decoder=enums.Speed)
FieldLoaderMixin.add_field(key=500, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=501, decoder=int)
FieldLoaderMixin.add_field(key=502, decoder=enums.ReverbPreset)
FieldLoaderMixin.add_field(key=503, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=504, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=505, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=506, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=507, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=508, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=509, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=510, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=511, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=512, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=513, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=514, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=515, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=516, decoder=int)
FieldLoaderMixin.add_field(key=517, decoder=int)
FieldLoaderMixin.add_field(key=518, decoder=int)
FieldLoaderMixin.add_field(key=519, decoder=int)
FieldLoaderMixin.add_field(key=520, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=521, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=522, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=523, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=524, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=525, decoder=enums.TargetPlayer)
FieldLoaderMixin.add_field(key=526, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=527, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=528, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=529, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=530, decoder=int)
FieldLoaderMixin.add_field(key=531, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=532, decoder=enums.Option)
FieldLoaderMixin.add_field(key=533, decoder=int)
FieldLoaderMixin.add_field(key=534, decoder=int)
FieldLoaderMixin.add_field(key=535, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=536, decoder=enums.KeyframeSpin)
FieldLoaderMixin.add_field(key=537, decoder=int)
FieldLoaderMixin.add_field(key=538, decoder=enums.EffectSpecialCenter)
FieldLoaderMixin.add_field(key=539, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=540, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=541, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=542, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=543, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=544, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=545, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=546, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=547, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=548, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=549, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=550, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=551, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=552, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=553, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=554, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=555, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=556, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=557, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=558, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=559, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=560, decoder=int)
FieldLoaderMixin.add_field(key=561, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=562, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=563, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=564, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=565, decoder=int)
FieldLoaderMixin.add_field(key=566, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=567, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=568, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=569, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=570, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=571, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=572, decoder=enums.AdvFollowInit)
FieldLoaderMixin.add_field(key=573, decoder=enums.Option)
FieldLoaderMixin.add_field(key=574, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=575, decoder=enums.Option)
FieldLoaderMixin.add_field(key=576, decoder=enums.Option)
FieldLoaderMixin.add_field(key=577, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=578, decoder=enums.ItemSignOp)
FieldLoaderMixin.add_field(key=579, decoder=enums.ItemSignOp)
FieldLoaderMixin.add_field(key=580, decoder=enums.StopMode)
FieldLoaderMixin.add_field(key=581, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=582, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=583, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=584, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=585, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=586, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=587, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=588, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=589, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=590, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=591, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=592, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=593, decoder=enums.Option)
FieldLoaderMixin.add_field(key=595, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=596, decoder=int)
FieldLoaderMixin.add_field(key=597, decoder=int)
FieldLoaderMixin.add_field(key=598, decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key=599, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key=600, decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key="kA1", decoder=int)
FieldLoaderMixin.add_field(key="kA2", decoder=enums.Gamemode)
FieldLoaderMixin.add_field(key="kA3", decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key="kA4", decoder=enums.Speed)
FieldLoaderMixin.add_field(key="kA5", decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key="kA6", decoder=int)
FieldLoaderMixin.add_field(key="kA7", decoder=int)
FieldLoaderMixin.add_field(key="kA8", decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key="kA9", decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key="kA10", decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key="kA11", decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key="kA12", decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key="kA13", decoder=float, encoder=from_float)
FieldLoaderMixin.add_field(key="kA14", decoder=GuidelineList.from_string, encoder=GuidelineList.to_string)
FieldLoaderMixin.add_field(key="kA15", decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key="kA16", decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key="kA17", decoder=int)
FieldLoaderMixin.add_field(key="kA18", decoder=int)
FieldLoaderMixin.add_field(key="kA19", decoder=int)
FieldLoaderMixin.add_field(key="kA20", decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key="kA21", decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key="kA22", decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key="kA23", decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key="kA24", decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key="kA25", decoder=int)
FieldLoaderMixin.add_field(key="kA26", decoder=int)
FieldLoaderMixin.add_field(key="kA27", decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key="kA28", decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key="kA29", decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key="kA31", decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key="kA32", decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key="kA33", decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key="kA34", decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key="kA35", decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key="kA36", decoder=int)
FieldLoaderMixin.add_field(key="kA37", decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key="kA38", decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key="kA39", decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key="kA40", decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key="kA41", decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key="kA42", decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key="kA43", decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key="kA44", decoder=int)
FieldLoaderMixin.add_field(key="kA45", decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key="kA46", decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key="kA47", decoder=int)
FieldLoaderMixin.add_field(key="kA48", decoder=to_bool, encoder=from_bool)
FieldLoaderMixin.add_field(key="kS1", decoder=int)
FieldLoaderMixin.add_field(key="kS2", decoder=int)
FieldLoaderMixin.add_field(key="kS3", decoder=int)
FieldLoaderMixin.add_field(key="kS4", decoder=int)
FieldLoaderMixin.add_field(key="kS5", decoder=int)
FieldLoaderMixin.add_field(key="kS6", decoder=int)
FieldLoaderMixin.add_field(key="kS7", decoder=int)
FieldLoaderMixin.add_field(key="kS8", decoder=int)
FieldLoaderMixin.add_field(key="kS9", decoder=int)
FieldLoaderMixin.add_field(key="kS10", decoder=int)
FieldLoaderMixin.add_field(key="kS11", decoder=int)
FieldLoaderMixin.add_field(key="kS12", decoder=int)
FieldLoaderMixin.add_field(key="kS13", decoder=int)
FieldLoaderMixin.add_field(key="kS14", decoder=int)
FieldLoaderMixin.add_field(key="kS15", decoder=int)
FieldLoaderMixin.add_field(key="kS16", decoder=enums.TargetPlayer)
FieldLoaderMixin.add_field(key="kS17", decoder=enums.TargetPlayer)
FieldLoaderMixin.add_field(key="kS18", decoder=enums.TargetPlayer)
FieldLoaderMixin.add_field(key="kS19", decoder=enums.TargetPlayer)
FieldLoaderMixin.add_field(key="kS20", decoder=enums.TargetPlayer)
FieldLoaderMixin.add_field(key="kS29", decoder=Color.from_string, encoder=Color.to_string)
FieldLoaderMixin.add_field(key="kS30", decoder=Color.from_string, encoder=Color.to_string)
FieldLoaderMixin.add_field(key="kS31", decoder=Color.from_string, encoder=Color.to_string)
FieldLoaderMixin.add_field(key="kS32", decoder=Color.from_string, encoder=Color.to_string)
FieldLoaderMixin.add_field(key="kS33", decoder=Color.from_string, encoder=Color.to_string)
FieldLoaderMixin.add_field(key="kS34", decoder=Color.from_string, encoder=Color.to_string)
FieldLoaderMixin.add_field(key="kS35", decoder=Color.from_string, encoder=Color.to_string)
FieldLoaderMixin.add_field(key="kS36", decoder=Color.from_string, encoder=Color.to_string)
FieldLoaderMixin.add_field(key="kS37", decoder=Color.from_string, encoder=Color.to_string)
FieldLoaderMixin.add_field(key="kS38", decoder=ColorList.from_string, encoder=ColorList.to_string)
FieldLoaderMixin.add_field(key="kS39", decoder=int)