name: Build and Deploy Docs

on:
  push:
    branches: [ main ]  # Automatically build docs on push to main
  workflow_dispatch:    # Allow manual trigger

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # important for setuptools-scm tags

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Step 3: Install dependencies for building docs
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-rtd-theme setuptools-scm

      # Step 4: Build HTML docs with Sphinx
      - name: Build HTML documentation
        run: |
          cd docs
          make html

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
          force_orphan: true
          keep_files: false

