name: Build Docs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-rtd-theme setuptools setuptools-scm
      
      - name: Install package for autodoc
        run: |
          python -m pip install -e .
      
      - name: Build HTML docs
        run: |
          cd docs
          make html
